---
name: instagram_clone
description: Instagram clone created using Flutter.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.6
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  provider: ^6.0.4
  uuid: ^3.0.7
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/ic_instagram.svg
